"""add CBT AI quota accounting

Revision ID: 20260930_cbt_ai_quota
Revises: 20260927_elective_groups
Create Date: 2026-09-30 16:01:12.407332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260930_cbt_ai_quota"
down_revision: Union[str, Sequence[str], None] = "20260927_elective_groups"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cbt_ai_tenant_credit_balances",
        sa.Column("available_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_credits >= 0", name="ck_cbt_ai_tenant_credit_balances_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_cbt_ai_tenant_credit_balances_tenant"),
        schema="public",
    )
    op.create_table(
        "cbt_ai_quota_accounts",
        sa.Column(
            "actor_type",
            sa.Enum("teacher", "tenant_admin", name="ai_quota_actor_type", schema="public"),
            nullable=False,
        ),
        sa.Column("teacher_membership_id", sa.UUID(), nullable=True),
        sa.Column("tenant_admin_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                actor_type = 'teacher'\n                AND teacher_membership_id IS NOT NULL\n                AND tenant_admin_id IS NULL\n            )\n            OR\n            (\n                actor_type = 'tenant_admin'\n                AND tenant_admin_id IS NOT NULL\n                AND teacher_membership_id IS NULL\n            )\n            ",
            name="ck_cbt_ai_quota_accounts_actor_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_membership_id"], ["public.teacher_memberships.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_admin_id"], ["public.tenant_admins.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_accounts_tenant_actor_type",
        "cbt_ai_quota_accounts",
        ["tenant_id", "actor_type"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "uq_cbt_ai_quota_accounts_teacher",
        "cbt_ai_quota_accounts",
        ["teacher_membership_id"],
        unique=True,
        schema="public",
        postgresql_where=sa.text("teacher_membership_id IS NOT NULL"),
    )
    op.create_index(
        "uq_cbt_ai_quota_accounts_tenant_admin",
        "cbt_ai_quota_accounts",
        ["tenant_admin_id"],
        unique=True,
        schema="public",
        postgresql_where=sa.text("tenant_admin_id IS NOT NULL"),
    )
    op.create_table(
        "cbt_ai_quota_purchases",
        sa.Column("initiated_by_admin_id", sa.UUID(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("amount_kobo", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "success",
                "failed",
                "cancelled",
                name="cbt_ai_quota_purchase_status",
                schema="public",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("credited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                status = 'success'\n                AND credited_at IS NOT NULL\n            )\n            OR\n            (\n                status <> 'success'\n                AND credited_at IS NULL\n            )\n            ",
            name="ck_cbt_ai_quota_purchases_credit_status_consistency",
        ),
        sa.CheckConstraint("amount_kobo > 0", name="ck_cbt_ai_quota_purchases_positive_amount"),
        sa.CheckConstraint("credits > 0", name="ck_cbt_ai_quota_purchases_positive_credits"),
        sa.ForeignKeyConstraint(
            ["initiated_by_admin_id"], ["public.tenant_admins.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("reference"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_purchases_admin",
        "cbt_ai_quota_purchases",
        ["initiated_by_admin_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_purchases_created",
        "cbt_ai_quota_purchases",
        ["tenant_id", "created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_purchases_tenant_status",
        "cbt_ai_quota_purchases",
        ["tenant_id", "status"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_credit_allocations",
        sa.Column("recipient_quota_account_id", sa.UUID(), nullable=False),
        sa.Column("allocated_by_admin_id", sa.UUID(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credits > 0", name="ck_cbt_ai_credit_allocations_positive_credits"),
        sa.ForeignKeyConstraint(
            ["allocated_by_admin_id"], ["public.tenant_admins.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["recipient_quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_allocations_admin",
        "cbt_ai_credit_allocations",
        ["allocated_by_admin_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_allocations_recipient",
        "cbt_ai_credit_allocations",
        ["recipient_quota_account_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_allocations_tenant_created",
        "cbt_ai_credit_allocations",
        ["tenant_id", "created_at"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_extra_credit_balances",
        sa.Column("quota_account_id", sa.UUID(), nullable=False),
        sa.Column("available_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_credits >= 0", name="ck_cbt_ai_extra_credit_balances_available_nonnegative"
        ),
        sa.CheckConstraint(
            "reserved_credits <= available_credits",
            name="ck_cbt_ai_extra_credit_balances_reserved_capacity",
        ),
        sa.CheckConstraint(
            "reserved_credits >= 0", name="ck_cbt_ai_extra_credit_balances_reserved_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("quota_account_id", name="uq_cbt_ai_extra_credit_balances_account"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_extra_credit_balances_tenant",
        "cbt_ai_extra_credit_balances",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_weekly_quotas",
        sa.Column("quota_account_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("credit_limit", sa.Integer(), server_default="100", nullable=False),
        sa.Column("used_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credit_limit >= 0", name="ck_cbt_ai_weekly_quotas_limit_nonnegative"),
        sa.CheckConstraint(
            "reserved_credits >= 0", name="ck_cbt_ai_weekly_quotas_reserved_nonnegative"
        ),
        sa.CheckConstraint(
            "used_credits + reserved_credits <= credit_limit",
            name="ck_cbt_ai_weekly_quotas_capacity",
        ),
        sa.CheckConstraint("used_credits >= 0", name="ck_cbt_ai_weekly_quotas_used_nonnegative"),
        sa.ForeignKeyConstraint(
            ["quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "quota_account_id", "week_start", name="uq_cbt_ai_weekly_quotas_account_week"
        ),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_weekly_quotas_tenant_week",
        "cbt_ai_weekly_quotas",
        ["tenant_id", "week_start"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_credit_reservations",
        sa.Column("quota_account_id", sa.UUID(), nullable=False),
        sa.Column("weekly_quota_id", sa.UUID(), nullable=True),
        sa.Column("reserved_free_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_extra_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("settled_free_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("settled_extra_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "settled",
                "released",
                "expired",
                name="cbt_ai_credit_reservation_status",
                schema="public",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                status = 'pending'\n                AND settled_at IS NULL\n                AND released_at IS NULL\n            )\n            OR\n            (\n                status = 'settled'\n                AND settled_at IS NOT NULL\n                AND released_at IS NULL\n            )\n            OR\n            (\n                status IN ('released', 'expired')\n                AND settled_at IS NULL\n                AND released_at IS NOT NULL\n            )\n            ",
            name="ck_cbt_ai_credit_reservations_status_consistency",
        ),
        sa.CheckConstraint(
            "reserved_extra_credits >= 0",
            name="ck_cbt_ai_credit_reservations_reserved_extra_nonnegative",
        ),
        sa.CheckConstraint(
            "reserved_free_credits + reserved_extra_credits > 0",
            name="ck_cbt_ai_credit_reservations_positive_total",
        ),
        sa.CheckConstraint(
            "reserved_free_credits >= 0",
            name="ck_cbt_ai_credit_reservations_reserved_free_nonnegative",
        ),
        sa.CheckConstraint(
            "settled_extra_credits <= reserved_extra_credits",
            name="ck_cbt_ai_credit_reservations_settled_extra_capacity",
        ),
        sa.CheckConstraint(
            "settled_extra_credits >= 0",
            name="ck_cbt_ai_credit_reservations_settled_extra_nonnegative",
        ),
        sa.CheckConstraint(
            "settled_free_credits <= reserved_free_credits",
            name="ck_cbt_ai_credit_reservations_settled_free_capacity",
        ),
        sa.CheckConstraint(
            "settled_free_credits >= 0",
            name="ck_cbt_ai_credit_reservations_settled_free_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weekly_quota_id"], ["public.cbt_ai_weekly_quotas.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_reservations_account_status",
        "cbt_ai_credit_reservations",
        ["quota_account_id", "status"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_reservations_pending_expiry",
        "cbt_ai_credit_reservations",
        ["expires_at"],
        unique=False,
        schema="public",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_cbt_ai_credit_reservations_tenant_status",
        "cbt_ai_credit_reservations",
        ["tenant_id", "status"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_quota_requests",
        sa.Column("requester_quota_account_id", sa.UUID(), nullable=False),
        sa.Column("requested_credits", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "cancelled",
                name="cbt_ai_quota_request_status",
                schema="public",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reviewed_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("approved_credits", sa.Integer(), nullable=True),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                status = 'pending'\n                AND reviewed_by_admin_id IS NULL\n                AND approved_credits IS NULL\n                AND allocation_id IS NULL\n                AND reviewed_at IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'approved'\n                AND reviewed_by_admin_id IS NOT NULL\n                AND approved_credits IS NOT NULL\n                AND allocation_id IS NOT NULL\n                AND reviewed_at IS NOT NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'rejected'\n                AND reviewed_by_admin_id IS NOT NULL\n                AND approved_credits IS NULL\n                AND allocation_id IS NULL\n                AND reviewed_at IS NOT NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'cancelled'\n                AND reviewed_by_admin_id IS NULL\n                AND approved_credits IS NULL\n                AND allocation_id IS NULL\n                AND reviewed_at IS NULL\n                AND cancelled_at IS NOT NULL\n            )\n            ",
            name="ck_cbt_ai_quota_requests_status_consistency",
        ),
        sa.CheckConstraint(
            "approved_credits IS NULL OR approved_credits <= requested_credits",
            name="ck_cbt_ai_quota_requests_approved_not_above_requested",
        ),
        sa.CheckConstraint(
            "approved_credits IS NULL OR approved_credits > 0",
            name="ck_cbt_ai_quota_requests_approved_positive",
        ),
        sa.CheckConstraint(
            "requested_credits > 0", name="ck_cbt_ai_quota_requests_requested_positive"
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["public.cbt_ai_credit_allocations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["requester_quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_id"], ["public.tenant_admins.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_requests_pending",
        "cbt_ai_quota_requests",
        ["tenant_id", "created_at"],
        unique=False,
        schema="public",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_cbt_ai_quota_requests_requester_status",
        "cbt_ai_quota_requests",
        ["requester_quota_account_id", "status"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_quota_requests_tenant_status",
        "cbt_ai_quota_requests",
        ["tenant_id", "status"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "cbt_ai_credit_ledger",
        sa.Column("quota_account_id", sa.UUID(), nullable=True),
        sa.Column(
            "bucket",
            sa.Enum(
                "weekly_free",
                "top_up",
                "tenant_reserve",
                name="cbt_ai_credit_ledger_bucket",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "purchase",
                "allocation_out",
                "allocation_in",
                "consumption",
                name="cbt_ai_credit_ledger_event_type",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column("credit_delta", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("purchase_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                bucket = 'tenant_reserve'\n                AND quota_account_id IS NULL\n            )\n            OR\n            (\n                bucket IN ('weekly_free', 'top_up')\n                AND quota_account_id IS NOT NULL\n            )\n            ",
            name="ck_cbt_ai_credit_ledger_bucket_owner",
        ),
        sa.CheckConstraint("credit_delta <> 0", name="ck_cbt_ai_credit_ledger_nonzero_delta"),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["public.cbt_ai_credit_allocations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"], ["public.cbt_ai_quota_purchases.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["quota_account_id"], ["public.cbt_ai_quota_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"], ["public.cbt_ai_credit_reservations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["public.tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_ledger_account_created",
        "cbt_ai_credit_ledger",
        ["quota_account_id", "created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_ledger_allocation",
        "cbt_ai_credit_ledger",
        ["allocation_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_ledger_purchase",
        "cbt_ai_credit_ledger",
        ["purchase_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_ledger_reservation",
        "cbt_ai_credit_ledger",
        ["reservation_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "ix_cbt_ai_credit_ledger_tenant_created",
        "cbt_ai_credit_ledger",
        ["tenant_id", "created_at"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cbt_ai_credit_ledger_tenant_created", table_name="cbt_ai_credit_ledger", schema="public"
    )
    op.drop_index(
        "ix_cbt_ai_credit_ledger_reservation", table_name="cbt_ai_credit_ledger", schema="public"
    )
    op.drop_index(
        "ix_cbt_ai_credit_ledger_purchase", table_name="cbt_ai_credit_ledger", schema="public"
    )
    op.drop_index(
        "ix_cbt_ai_credit_ledger_allocation", table_name="cbt_ai_credit_ledger", schema="public"
    )
    op.drop_index(
        "ix_cbt_ai_credit_ledger_account_created",
        table_name="cbt_ai_credit_ledger",
        schema="public",
    )
    op.drop_table("cbt_ai_credit_ledger", schema="public")
    op.drop_index(
        "ix_cbt_ai_quota_requests_tenant_status",
        table_name="cbt_ai_quota_requests",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_quota_requests_requester_status",
        table_name="cbt_ai_quota_requests",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_quota_requests_pending",
        table_name="cbt_ai_quota_requests",
        schema="public",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("cbt_ai_quota_requests", schema="public")
    op.drop_index(
        "ix_cbt_ai_credit_reservations_tenant_status",
        table_name="cbt_ai_credit_reservations",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_credit_reservations_pending_expiry",
        table_name="cbt_ai_credit_reservations",
        schema="public",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_cbt_ai_credit_reservations_account_status",
        table_name="cbt_ai_credit_reservations",
        schema="public",
    )
    op.drop_table("cbt_ai_credit_reservations", schema="public")
    op.drop_index(
        "ix_cbt_ai_weekly_quotas_tenant_week", table_name="cbt_ai_weekly_quotas", schema="public"
    )
    op.drop_table("cbt_ai_weekly_quotas", schema="public")
    op.drop_index(
        "ix_cbt_ai_extra_credit_balances_tenant",
        table_name="cbt_ai_extra_credit_balances",
        schema="public",
    )
    op.drop_table("cbt_ai_extra_credit_balances", schema="public")
    op.drop_index(
        "ix_cbt_ai_credit_allocations_tenant_created",
        table_name="cbt_ai_credit_allocations",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_credit_allocations_recipient",
        table_name="cbt_ai_credit_allocations",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_credit_allocations_admin",
        table_name="cbt_ai_credit_allocations",
        schema="public",
    )
    op.drop_table("cbt_ai_credit_allocations", schema="public")
    op.drop_index(
        "ix_cbt_ai_quota_purchases_tenant_status",
        table_name="cbt_ai_quota_purchases",
        schema="public",
    )
    op.drop_index(
        "ix_cbt_ai_quota_purchases_created", table_name="cbt_ai_quota_purchases", schema="public"
    )
    op.drop_index(
        "ix_cbt_ai_quota_purchases_admin", table_name="cbt_ai_quota_purchases", schema="public"
    )
    op.drop_table("cbt_ai_quota_purchases", schema="public")
    op.drop_index(
        "uq_cbt_ai_quota_accounts_tenant_admin",
        table_name="cbt_ai_quota_accounts",
        schema="public",
        postgresql_where=sa.text("tenant_admin_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_cbt_ai_quota_accounts_teacher",
        table_name="cbt_ai_quota_accounts",
        schema="public",
        postgresql_where=sa.text("teacher_membership_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_cbt_ai_quota_accounts_tenant_actor_type",
        table_name="cbt_ai_quota_accounts",
        schema="public",
    )
    op.drop_table("cbt_ai_quota_accounts", schema="public")
    op.drop_table("cbt_ai_tenant_credit_balances", schema="public")
    # ### end Alembic commands ###
