"""empty message

Revision ID: 99c9e8ec3bb4
Revises: 20260818_cbt_sync_v3
Create Date: 2026-08-25 19:43:53.306243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c9e8ec3bb4'
down_revision: Union[str, Sequence[str], None] = '20260818_cbt_sync_v3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_levels', sa.Column('specialization_required_from_term_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_levels', 'specialization_required_from_term_position')
    # ### end Alembic commands ###
