import { useEffect, useMemo, useState } from "react";
import Button from "../../components/ui/Button";
import { useToast } from "../../hooks/useToast";
import { academicLevelService } from "../../services/academicsService";
import { curriculumService } from "../../services/curriculumService";
import { subjectService } from "../../services/subject.service";
import { getErrorMessage } from "../../services/api";
import { SelectControl, WorkspaceGrid, WorkspacePanel } from "./AcademicWorkspacePrimitives";

const items=(value)=>Array.isArray(value)?value:value?.items||[];
export default function CurriculumWorkspace(){
 const {showError,showSuccess}=useToast(); const [levels,setLevels]=useState([]); const [subjects,setSubjects]=useState([]); const [levelId,setLevelId]=useState(""); const [curriculum,setCurriculum]=useState(null); const [subjectId,setSubjectId]=useState(""); const [elective,setElective]=useState(false); const [saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([academicLevelService.getLevels({activeOnly:true}),subjectService.getSubjects({limit:500})]).then(([l,s])=>{const levelRows=items(l);setLevels(levelRows);setLevelId(x=>x||levelRows[0]?.id||"");setSubjects(items(s));}).catch(e=>showError(getErrorMessage(e,"Could not load curriculum setup.")));},[showError]);
 useEffect(()=>{if(!levelId){setCurriculum(null);return;} curriculumService.getCurriculum(levelId).then(setCurriculum).catch(e=>showError(getErrorMessage(e,"Could not load curriculum.")));},[levelId,showError]);
 const attached=useMemo(()=>new Set((curriculum?.subjects||[]).map(x=>x.subject_id)),[curriculum]); const available=subjects.filter(x=>!attached.has(x.id)&&x.is_active!==false&&!x.archived_at);
 const add=async(e)=>{e.preventDefault();if(!subjectId)return;setSaving(true);try{await curriculumService.addSubject(levelId,{subject_id:subjectId,is_elective:elective});setCurriculum(await curriculumService.getCurriculum(levelId));setSubjectId("");setElective(false);showSuccess("Subject added to curriculum.");}catch(err){showError(getErrorMessage(err,"Could not add subject."));}finally{setSaving(false);}};
 const toggle=async(row)=>{try{await curriculumService.updateSubject(row.id,{is_elective:!row.is_elective});setCurriculum(await curriculumService.getCurriculum(levelId));showSuccess(row.is_elective?"Subject is now compulsory.":"Subject is now elective.");}catch(err){showError(getErrorMessage(err,"Could not update curriculum subject."));}};
 return <WorkspaceGrid editor={<WorkspacePanel title="Add curriculum subject" description="Subjects are compulsory by default. Mark only genuinely optional subjects as elective."><form className="space-y-3" onSubmit={add}><SelectControl label="Academic level" value={levelId} onChange={setLevelId} options={levels.map(x=>({value:x.id,label:x.name}))} required/><SelectControl label="Subject" value={subjectId} onChange={setSubjectId} options={available.map(x=>({value:x.id,label:x.name}))} required/><label className="flex items-center gap-2 text-sm font-medium text-text"><input type="checkbox" checked={elective} onChange={e=>setElective(e.target.checked)}/> Elective subject</label><Button type="submit" disabled={saving||!subjectId}>{saving?"Saving…":"Add to curriculum"}</Button></form></WorkspacePanel>} content={<WorkspacePanel title={curriculum?.level_name?`${curriculum.level_name} curriculum`:"Curriculum"} description="This curriculum is shared by every class arm in the level."><div className="space-y-2">{(curriculum?.subjects||[]).map(row=><div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-border/70 px-3 py-3"><div><p className="font-semibold text-text">{row.subject_name}</p><p className="text-xs text-text-muted">{row.is_elective?"Elective":"Compulsory"}</p></div><Button size="small" variant="outline" onClick={()=>toggle(row)}>{row.is_elective?"Make compulsory":"Make elective"}</Button></div>)}{curriculum?.subjects?.length===0?<p className="text-sm text-text-muted">No subjects have been added yet.</p>:null}</div></WorkspacePanel>}/>;
}
