import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(__dirname, "../..");

const readSource = (relativePath) =>
  readFile(path.join(frontendRoot, relativePath), "utf8");

test("bulk import uses the shared authenticated transport and deduplicates polling", async () => {
  const source = await readSource("src/services/bulkImport.service.js");

  assert.match(source, /api\.postForm\(/);
  assert.match(source, /api\.getBlob\(/);
  assert.match(source, /inFlightJobRequests/);
  assert.match(source, /ERROR_POLL_CACHE_MS/);
  assert.doesNotMatch(source, /\bfetch\s*\(/);
});

test("subscription guards do not treat missing entitlements as confirmed access", async () => {
  const source = await readSource("src/features/subscriptions/SubscriptionProvider.jsx");

  assert.match(source, /visibleErrors\.entitlements/);
  assert.match(source, /allowed:\s*false,[\s\S]*We couldn't confirm access for this feature/);
  assert.match(source, /allowed:\s*false,[\s\S]*We couldn't confirm your plan limits/);
});

test("modal traps keyboard focus and restores the previously focused element", async () => {
  const source = await readSource("src/components/ui/Modal.jsx");

  assert.match(source, /FOCUSABLE_SELECTOR/);
  assert.match(source, /previouslyFocusedRef/);
  assert.match(source, /event\.key !== "Tab"/);
  assert.match(source, /previous\.focus\(\{ preventScroll: true \}\)/);
  assert.match(source, /tabIndex=\{-1\}/);
});

test("calendar actions use toast success feedback instead of an inline success banner", async () => {
  const source = await readSource("src/features/schoolCalendar/components/SchoolCalendarWorkspace.jsx");

  assert.match(source, /useToast/);
  assert.match(source, /showSuccess\(successMessage\)/);
  assert.doesNotMatch(source, /setMessage\(/);
  assert.doesNotMatch(source, /<Notice tone="success"/);
});

test("invitation feedback avoids transport and queue terminology", async () => {
  const source = await readSource("src/pages/admin/AdminInvitationPage.jsx");

  assert.match(source, /Invitation created and ready for delivery\./);
  assert.match(source, /invitation is on its way\./);
  assert.doesNotMatch(source, /accepted by the API/i);
  assert.doesNotMatch(source, /Queueing invitation/i);
  assert.doesNotMatch(source, /delivery remains asynchronous/i);
});

test("student creation copy describes outcomes instead of implementation details", async () => {
  const source = await readSource("src/pages/admin/StudentCreatePage.jsx");

  assert.match(source, /admission number and first-login code are created automatically/i);
  assert.match(source, /Parent invitations are on their way\./);
  assert.doesNotMatch(source, /generated by the backend/i);
  assert.doesNotMatch(source, /invitations queued/i);
  assert.doesNotMatch(source, /atomically/i);
});
