import { useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  Download,
  FileSpreadsheet,
  History,
  MailCheck,
  RefreshCw,
  RotateCcw,
  UploadCloud,
  Users,
} from "lucide-react";

import DashboardLayout from "../../components/layout/DashboardLayout";
import Button from "../../components/ui/Button";
import Badge from "../../components/ui/Badge";
import Card from "../../components/ui/Card";
import EmptyState from "../../components/shared/EmptyState";
import LoadingState from "../../components/shared/LoadingState";
import { bulkImportService } from "../../services/bulkImport.service";
import { getErrorMessage } from "../../services/api";

const RESOURCE_OPTIONS = [
  {
    key: "students",
    label: "Students",
    icon: Users,
    description: "Create student profiles from a signed XLSX template. Admission numbers and setup codes are generated by the backend.",
    notes: ["Class placement uses class_name and optional class_arm.", "Date of birth is required.", "Setup codes appear after confirmation."],
  },
  {
    key: "teachers",
    label: "Teachers",
    icon: FileSpreadsheet,
    description: "Create teacher accounts and queue invite emails in the background.",
    notes: ["Email is required.", "Staff IDs are normalized.", "Invites are sent through the worker."],
  },
  {
    key: "parents",
    label: "Parents",
    icon: MailCheck,
    description: "Create parent accounts and queue invite emails through the safe email outbox.",
    notes: ["Email is required.", "Parent-student linking stays separate.", "Delivery progress is visible after confirmation."],
  },
];

const getResultRows = (job) => Array.isArray(job?.metadata_json?.result_rows) ? job.metadata_json.result_rows : [];

const percent = (value, total) => {
  const safeTotal = Number(total || 0);
  if (!safeTotal) return 0;
  return Math.min(100, Math.round((Number(value || 0) / safeTotal) * 100));
};

const formatDate = (value) => {
  if (!value) return "--";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "--";
  return date.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
};

function ProgressBar({ value = 0 }) {
  return (
    <div className="h-2 overflow-hidden rounded-full bg-surface-muted">
      <div className="h-full rounded-full bg-gradient-to-r from-primary to-accent transition-all" style={{ width: `${Math.max(4, value)}%` }} />
    </div>
  );
}

function ResourceCard({ option, active, onSelect, onDownload, isDownloading }) {
  const Icon = option.icon;
  return (
    <Card as="button" type="button" onClick={() => onSelect(option.key)} className={`w-full p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/40 ${active ? "border-primary/50 bg-primary-soft/30 ring-2 ring-primary/10" : ""}`}>
      <div className="flex items-start gap-3">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary-soft text-primary">
          <Icon className="h-5 w-5" />
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="font-semibold text-text">{option.label}</h3>
            {active ? <Badge variant="primary">Selected</Badge> : null}
          </div>
          <p className="mt-2 text-sm leading-6 text-text-muted">{option.description}</p>
        </div>
      </div>
      <div className="mt-4 flex flex-col gap-2 sm:flex-row">
        <Button size="sm" variant={active ? "primary" : "outline"} className="w-full sm:w-auto" onClick={(event) => { event.stopPropagation(); onDownload(option.key); }} disabled={isDownloading}>
          <Download className="h-4 w-4" />
          Template
        </Button>
      </div>
    </Card>
  );
}

function JobSummary({ job }) {
  if (!job) return null;
  const completion = percent(job.processed_rows, job.total_rows);
  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h2 className="section-title">Dry-run summary</h2>
            <Badge variant={job.failed_rows > 0 ? "warning" : "success"}>{job.status}</Badge>
          </div>
          <p className="mt-1 text-sm text-text-muted">Review the validation result before creating records.</p>
        </div>
        <div className="grid grid-cols-3 gap-2 text-center sm:min-w-[20rem]">
          <div className="rounded-2xl border border-border bg-surface-muted/20 p-3">
            <p className="text-xs text-text-muted">Rows</p>
            <p className="mt-1 font-semibold">{job.total_rows}</p>
          </div>
          <div className="rounded-2xl border border-border bg-success-soft p-3">
            <p className="text-xs text-text-muted">Valid</p>
            <p className="mt-1 font-semibold text-success">{job.successful_rows}</p>
          </div>
          <div className="rounded-2xl border border-border bg-error-soft p-3">
            <p className="text-xs text-text-muted">Invalid</p>
            <p className="mt-1 font-semibold text-error">{job.failed_rows}</p>
          </div>
        </div>
      </div>
      <div className="mt-5">
        <ProgressBar value={completion} />
        <p className="mt-2 text-xs text-text-muted">{completion}% processed in validation</p>
      </div>
    </Card>
  );
}

function ErrorPreview({ job, onDownloadResult }) {
  const rows = getResultRows(job);
  const failedRows = rows.filter((row) => row.status === "failed").slice(0, 8);

  if (!job) return null;

  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="section-title">Validation details</h2>
          <p className="mt-1 text-sm text-text-muted">Invalid rows are shown first. Download the result file for the full report.</p>
        </div>
        <Button variant="outline" size="sm" onClick={onDownloadResult} disabled={!job?.id}>
          <Download className="h-4 w-4" />
          Result report
        </Button>
      </div>

      {failedRows.length === 0 ? (
        <div className="mt-5 rounded-2xl border border-success/30 bg-success-soft p-4 text-sm text-success">
          No validation errors found. You can confirm this import.
        </div>
      ) : (
        <div className="mt-5 grid gap-3">
          {failedRows.map((row) => (
            <div key={row.row_number} className="rounded-2xl border border-error/20 bg-error-soft/40 p-4">
              <div className="flex items-start gap-3">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-error" />
                <div>
                  <p className="text-sm font-semibold text-error">Row {row.row_number}</p>
                  <p className="mt-1 text-sm leading-6 text-text-soft">{row.error_message || "This row failed validation."}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}

function EmailStatusPanel({ summary, onRefresh, onRecover, onRetry, loading }) {
  if (!summary) return null;
  const total = Number(summary.total || 0);
  const sentPercent = percent(summary.sent, total);
  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="section-title">Email delivery</h2>
          <p className="mt-1 text-sm text-text-muted">Invite emails are sent in small background batches so the app stays usable.</p>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row">
          <Button variant="outline" size="sm" onClick={onRefresh} disabled={loading}><RefreshCw className="h-4 w-4" />Refresh</Button>
          <Button variant="outline" size="sm" onClick={onRecover} disabled={loading}><RotateCcw className="h-4 w-4" />Recover stuck</Button>
          <Button variant="outline" size="sm" onClick={onRetry} disabled={loading}>Retry failed</Button>
        </div>
      </div>
      <div className="mt-5">
        <ProgressBar value={sentPercent} />
        <p className="mt-2 text-xs text-text-muted">{sentPercent}% sent</p>
      </div>
      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">
        {[
          ["Sent", summary.sent, "text-success"],
          ["Pending", summary.pending, "text-text"],
          ["Processing", summary.processing, "text-primary"],
          ["Failed", summary.failed, "text-error"],
          ["Total", summary.total, "text-text"],
        ].map(([label, value, tone]) => (
          <div key={label} className="rounded-2xl border border-border bg-surface-muted/20 p-3">
            <p className="text-xs text-text-muted">{label}</p>
            <p className={`mt-1 text-lg font-semibold ${tone}`}>{value ?? 0}</p>
          </div>
        ))}
      </div>
    </Card>
  );
}

function JobHistory({ jobs }) {
  return (
    <Card className="p-5 sm:p-6">
      <div className="flex items-center gap-2">
        <History className="h-5 w-5 text-primary" />
        <h2 className="section-title">Recent import jobs</h2>
      </div>
      <div className="mt-4 grid gap-3">
        {jobs.length === 0 ? (
          <EmptyState title="No imports yet" description="Your recent bulk import jobs will appear here." />
        ) : jobs.map((job) => (
          <div key={job.id} className="rounded-2xl border border-border bg-surface-muted/20 p-4">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-sm font-semibold capitalize">{job.resource_type}</p>
                <p className="mt-1 text-xs text-text-muted">{formatDate(job.created_at)} · {job.original_filename}</p>
              </div>
              <div className="grid grid-cols-3 gap-2 text-center sm:min-w-[16rem]">
                <span className="rounded-xl bg-surface px-3 py-2 text-xs">Rows {job.total_rows}</span>
                <span className="rounded-xl bg-success-soft px-3 py-2 text-xs text-success">Ok {job.successful_rows}</span>
                <span className="rounded-xl bg-error-soft px-3 py-2 text-xs text-error">Bad {job.failed_rows}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}

function BulkImportPage() {
  const [activeResource, setActiveResource] = useState("parents");
  const [file, setFile] = useState(null);
  const [currentJob, setCurrentJob] = useState(null);
  const [emailSummary, setEmailSummary] = useState(null);
  const [jobs, setJobs] = useState([]);
  const [error, setError] = useState("");
  const [statusMessage, setStatusMessage] = useState("");
  const [loadingState, setLoadingState] = useState("idle");

  const selectedResource = useMemo(
    () => RESOURCE_OPTIONS.find((option) => option.key === activeResource) || RESOURCE_OPTIONS[0],
    [activeResource],
  );

  const loadJobs = async () => {
    try {
      const response = await bulkImportService.listJobs();
      setJobs(Array.isArray(response?.items) ? response.items : []);
    } catch {
      setJobs([]);
    }
  };

  useEffect(() => {
    loadJobs();
  }, []);

  const handleDownloadTemplate = async (resourceType = activeResource) => {
    setError("");
    setLoadingState("template");
    try {
      await bulkImportService.downloadTemplate(resourceType);
      setStatusMessage("Template downloaded. Fill it without changing the headers.");
    } catch (err) {
      setError(getErrorMessage(err, "Template download failed."));
    } finally {
      setLoadingState("idle");
    }
  };

  const handleDryRun = async () => {
    if (!file) {
      setError("Choose the completed XLSX template before running dry-run.");
      return;
    }

    setError("");
    setStatusMessage("Validating file...");
    setLoadingState("dry-run");
    try {
      const job = await bulkImportService.dryRun(activeResource, file);
      setCurrentJob(job);
      setEmailSummary(null);
      setStatusMessage("Dry-run completed. Review the summary before confirming.");
      await loadJobs();
    } catch (err) {
      setError(getErrorMessage(err, "Dry-run failed."));
    } finally {
      setLoadingState("idle");
    }
  };

  const refreshEmailSummary = async (job = currentJob) => {
    if (!job?.id || !["parents", "teachers"].includes(job.resource_type)) return;
    const summary = await bulkImportService.getEmailSummary({ source: "bulk_import" });
    setEmailSummary(summary);
  };

  const handleConfirm = async () => {
    if (!currentJob?.id || Number(currentJob.successful_rows || 0) <= 0) return;
    setError("");
    setStatusMessage("Creating records. This can take a few minutes for large files...");
    setLoadingState("confirm");
    try {
      const job = await bulkImportService.confirm(currentJob.id);
      setCurrentJob(job);
      setStatusMessage("Import confirmed. Records were created and dashboard cache was cleared.");
      await Promise.all([loadJobs(), refreshEmailSummary(job)]);
    } catch (err) {
      setError(getErrorMessage(err, "Import confirmation failed."));
    } finally {
      setLoadingState("idle");
    }
  };

  const handleDownloadResult = async () => {
    if (!currentJob?.id) return;
    try {
      await bulkImportService.downloadResult(currentJob.id);
    } catch (err) {
      setError(getErrorMessage(err, "Result download failed."));
    }
  };

  const recoverStale = async () => {
    setLoadingState("email");
    try {
      await bulkImportService.recoverStaleEmails();
      await refreshEmailSummary();
    } catch (err) {
      setError(getErrorMessage(err, "Could not recover stale emails."));
    } finally {
      setLoadingState("idle");
    }
  };

  const retryFailed = async () => {
    setLoadingState("email");
    try {
      await bulkImportService.retryFailedEmails();
      await refreshEmailSummary();
    } catch (err) {
      setError(getErrorMessage(err, "Could not retry failed emails."));
    } finally {
      setLoadingState("idle");
    }
  };

  const busy = loadingState !== "idle";

  return (
    <DashboardLayout
      role="admin"
      title="Bulk Imports"
      description="Create students, teachers, and parents from backend-generated XLSX templates with dry-run validation first."
      actions={<Button variant="outline" onClick={() => handleDownloadTemplate(activeResource)} disabled={busy}><Download className="h-4 w-4" />Download template</Button>}
    >
      {error ? <div className="rounded-2xl border border-error/30 bg-error-soft px-4 py-3 text-sm font-medium text-error">{error}</div> : null}
      {statusMessage ? <div className="rounded-2xl border border-primary/20 bg-primary-soft/30 px-4 py-3 text-sm font-medium text-text-soft">{statusMessage}</div> : null}

      <section className="grid gap-4 lg:grid-cols-3">
        {RESOURCE_OPTIONS.map((option) => (
          <ResourceCard
            key={option.key}
            option={option}
            active={option.key === activeResource}
            onSelect={(key) => { setActiveResource(key); setFile(null); setCurrentJob(null); setEmailSummary(null); }}
            onDownload={handleDownloadTemplate}
            isDownloading={loadingState === "template"}
          />
        ))}
      </section>

      <section className="dashboard-grid lg:grid-cols-[minmax(0,1.05fr)_minmax(300px,0.95fr)]">
        <Card className="p-5 sm:p-6">
          <div className="flex flex-col gap-4">
            <div>
              <h2 className="section-title">Upload completed template</h2>
              <p className="mt-1 text-sm text-text-muted">Selected import: <span className="font-semibold text-text">{selectedResource.label}</span></p>
            </div>
            <label className="flex cursor-pointer flex-col items-center justify-center rounded-[1.75rem] border border-dashed border-border bg-surface-muted/20 px-4 py-8 text-center transition hover:border-primary/50 hover:bg-primary-soft/20">
              <UploadCloud className="h-10 w-10 text-primary" />
              <span className="mt-3 text-sm font-semibold text-text">{file ? file.name : "Choose XLSX file"}</span>
              <span className="mt-1 text-xs text-text-muted">Only backend-generated .xlsx templates are accepted.</span>
              <input type="file" accept=".xlsx" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] || null)} />
            </label>
            <div className="grid gap-3 sm:grid-cols-2">
              <Button variant="outline" onClick={() => handleDownloadTemplate(activeResource)} disabled={busy}><Download className="h-4 w-4" />Download fresh template</Button>
              <Button onClick={handleDryRun} disabled={busy || !file}>{loadingState === "dry-run" ? <RefreshCw className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Run dry-run</Button>
            </div>
          </div>
        </Card>

        <Card className="p-5 sm:p-6">
          <h2 className="section-title">How this works</h2>
          <div className="mt-4 grid gap-3">
            {["Download the signed XLSX template.", "Fill rows without changing headers.", "Run dry-run to catch row errors.", "Confirm only valid staged rows.", "Monitor invite email delivery."].map((item, index) => (
              <div key={item} className="flex gap-3 rounded-2xl border border-border bg-surface-muted/20 px-4 py-3">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">{index + 1}</span>
                <p className="text-sm leading-6 text-text-soft">{item}</p>
              </div>
            ))}
          </div>
        </Card>
      </section>

      {loadingState === "confirm" ? <LoadingState label="Creating records. Large imports can take a few minutes..." /> : null}

      <JobSummary job={currentJob} />
      <ErrorPreview job={currentJob} onDownloadResult={handleDownloadResult} />

      {currentJob?.id && Number(currentJob.successful_rows || 0) > 0 && currentJob.metadata_json?.dry_run !== false ? (
        <Card className="p-5 sm:p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="section-title">Ready to confirm</h2>
              <p className="mt-1 text-sm text-text-muted">This will create {currentJob.successful_rows} {currentJob.resource_type} records. Invite emails will be queued where applicable.</p>
            </div>
            <Button className="w-full sm:w-auto" onClick={handleConfirm} disabled={busy}>{loadingState === "confirm" ? <RefreshCw className="h-4 w-4 animate-spin" /> : null}Confirm import</Button>
          </div>
        </Card>
      ) : null}

      <EmailStatusPanel
        summary={emailSummary}
        onRefresh={() => refreshEmailSummary()}
        onRecover={recoverStale}
        onRetry={retryFailed}
        loading={loadingState === "email"}
      />

      <JobHistory jobs={jobs} />
    </DashboardLayout>
  );
}

export default BulkImportPage;
