import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import {
  AlertCircle,
  CheckCircle2,
  Download,
  FileSpreadsheet,
  History,
  MailCheck,
  RefreshCw,
  RotateCcw,
  UploadCloud,
  Users,
} from "lucide-react";

import DashboardLayout from "../../components/layout/DashboardLayout";
import Button from "../../components/ui/Button";
import Badge from "../../components/ui/Badge";
import Card from "../../components/ui/Card";
import EmptyState from "../../components/shared/EmptyState";
import LoadingState from "../../components/shared/LoadingState";
import { useToast } from "../../hooks/useToast";
import { bulkImportService } from "../../services/bulkImport.service";
import { getErrorMessage } from "../../services/api";

const ACTIVE_IMPORT_JOB_STORAGE_KEY = "learnly:active-import-job";
const ACTIVE_JOB_STATUSES = new Set(["pending", "processing"]);
const FINISHED_JOB_STATUSES = new Set(["completed", "partially_completed", "failed", "cancelled"]);

const RESOURCE_OPTIONS = [
  {
    key: "students",
    label: "Students",
    icon: Users,
    description: "Create student profiles from a signed XLSX template. Admission numbers and setup codes are generated by the backend.",
  },
  {
    key: "teachers",
    label: "Teachers",
    icon: FileSpreadsheet,
    description: "Create teacher accounts and queue invite emails in the background.",
  },
  {
    key: "parents",
    label: "Parents",
    icon: MailCheck,
    description: "Create parent accounts and queue invite emails through the safe email outbox.",
  },
];

const getResultRows = (job) => Array.isArray(job?.metadata_json?.result_rows) ? job.metadata_json.result_rows : [];
const isActiveJob = (job) => job?.id && ACTIVE_JOB_STATUSES.has(String(job.status || "").toLowerCase());
const isFinishedJob = (job) => job?.id && FINISHED_JOB_STATUSES.has(String(job.status || "").toLowerCase());

const percent = (value, total) => {
  const safeTotal = Number(total || 0);
  if (!safeTotal) return 0;
  return Math.min(100, Math.round((Number(value || 0) / safeTotal) * 100));
};

const formatDate = (value) => {
  if (!value) return "--";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "--";
  return date.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
};

function ProgressBar({ value = 0 }) {
  return (
    <div className="h-2 overflow-hidden rounded-full bg-surface-muted">
      <div className="h-full rounded-full bg-gradient-to-r from-primary to-accent transition-all duration-500" style={{ width: `${Math.max(4, value)}%` }} />
    </div>
  );
}

function ResourceCard({ option, active, onSelect, onDownload, isDownloading }) {
  const Icon = option.icon;
  return (
    <Card as="button" type="button" onClick={() => onSelect(option.key)} className={`w-full p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/40 ${active ? "border-primary/50 bg-primary-soft/30 ring-2 ring-primary/10" : ""}`}>
      <div className="flex items-start gap-3">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary-soft text-primary">
          <Icon className="h-5 w-5" />
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="font-semibold text-text">{option.label}</h3>
            {active ? <Badge variant="primary">Selected</Badge> : null}
          </div>
          <p className="mt-2 text-sm leading-6 text-text-muted">{option.description}</p>
        </div>
      </div>
      <div className="mt-4 flex flex-col gap-2 sm:flex-row">
        <Button size="sm" variant={active ? "primary" : "outline"} className="w-full sm:w-auto" onClick={(event) => { event.stopPropagation(); onDownload(option.key); }} disabled={isDownloading}>
          <Download className="h-4 w-4" />
          Template
        </Button>
      </div>
    </Card>
  );
}

function JobSummary({ job, onClear }) {
  if (!job) return null;

  const completion = percent(job.processed_rows, job.total_rows);
  const liveImport = job.metadata_json?.live_progress || job.metadata_json?.dry_run === false;
  const title = liveImport ? "Live import progress" : "Dry-run summary";
  const description = liveImport
    ? "This progress is loaded from the backend job record and survives refresh."
    : "Review the validation result before creating records.";

  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h2 className="section-title">{title}</h2>
            <Badge variant={job.failed_rows > 0 ? "warning" : isActiveJob(job) ? "primary" : "success"}>{job.status}</Badge>
          </div>
          <p className="mt-1 text-sm text-text-muted">{description}</p>
        </div>
        <div className="grid grid-cols-3 gap-2 text-center sm:min-w-[20rem]">
          <div className="rounded-2xl border border-border bg-surface-muted/20 p-3">
            <p className="text-xs text-text-muted">Processed</p>
            <p className="mt-1 font-semibold">{job.processed_rows}/{job.total_rows}</p>
          </div>
          <div className="rounded-2xl border border-border bg-success-soft p-3">
            <p className="text-xs text-text-muted">Created</p>
            <p className="mt-1 font-semibold text-success">{job.successful_rows}</p>
          </div>
          <div className="rounded-2xl border border-border bg-error-soft p-3">
            <p className="text-xs text-text-muted">Failed</p>
            <p className="mt-1 font-semibold text-error">{job.failed_rows}</p>
          </div>
        </div>
      </div>
      <div className="mt-5">
        <ProgressBar value={completion} />
        <div className="mt-2 flex flex-col gap-2 text-xs text-text-muted sm:flex-row sm:items-center sm:justify-between">
          <span>{completion}% complete</span>
          {job.metadata_json?.last_progress_at ? <span>Last update: {formatDate(job.metadata_json.last_progress_at)}</span> : null}
        </div>
      </div>
      {job.id ? (
        <div className="mt-5 flex flex-col gap-2 sm:flex-row sm:justify-end">
          <Button variant="outline" size="sm" onClick={onClear}>Clear current import</Button>
        </div>
      ) : null}
    </Card>
  );
}

function ErrorPreview({ job, onDownloadResult }) {
  const rows = getResultRows(job);
  const failedRows = rows.filter((row) => row.status === "failed").slice(0, 8);

  if (!job) return null;

  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="section-title">Validation details</h2>
          <p className="mt-1 text-sm text-text-muted">Invalid rows are shown first. Download the result file for the full report.</p>
        </div>
        <Button variant="outline" size="sm" onClick={onDownloadResult} disabled={!job?.id}>
          <Download className="h-4 w-4" />
          Result report
        </Button>
      </div>

      {failedRows.length === 0 ? (
        <div className="mt-5 rounded-2xl border border-success/30 bg-success-soft p-4 text-sm text-success">
          No validation errors found so far.
        </div>
      ) : (
        <div className="mt-5 grid gap-3">
          {failedRows.map((row) => (
            <div key={row.row_number} className="rounded-2xl border border-error/20 bg-error-soft/40 p-4">
              <div className="flex items-start gap-3">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-error" />
                <div>
                  <p className="text-sm font-semibold text-error">Row {row.row_number}</p>
                  <p className="mt-1 text-sm leading-6 text-text-soft">{row.error_message || "This row failed validation."}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}

function EmailStatusPanel({ summary, onRefresh, onRecover, onRetry, loading }) {
  if (!summary) return null;
  const total = Number(summary.total || 0);
  const sentPercent = percent(summary.sent, total);
  return (
    <Card className="p-5 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="section-title">Email delivery</h2>
          <p className="mt-1 text-sm text-text-muted">Invite emails are sent in small background batches so the app stays usable.</p>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row">
          <Button variant="outline" size="sm" onClick={onRefresh} disabled={loading}><RefreshCw className="h-4 w-4" />Refresh</Button>
          <Button variant="outline" size="sm" onClick={onRecover} disabled={loading}><RotateCcw className="h-4 w-4" />Recover stuck</Button>
          <Button variant="outline" size="sm" onClick={onRetry} disabled={loading}>Retry failed</Button>
        </div>
      </div>
      <div className="mt-5">
        <ProgressBar value={sentPercent} />
        <p className="mt-2 text-xs text-text-muted">{sentPercent}% sent</p>
      </div>
      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">
        {[
          ["Sent", summary.sent, "text-success"],
          ["Pending", summary.pending, "text-text"],
          ["Processing", summary.processing, "text-primary"],
          ["Failed", summary.failed, "text-error"],
          ["Total", summary.total, "text-text"],
        ].map(([label, value, tone]) => (
          <div key={label} className="rounded-2xl border border-border bg-surface-muted/20 p-3">
            <p className="text-xs text-text-muted">{label}</p>
            <p className={`mt-1 text-lg font-semibold ${tone}`}>{value ?? 0}</p>
          </div>
        ))}
      </div>
    </Card>
  );
}

function JobHistory({ jobs, onSelectJob }) {
  return (
    <Card className="p-5 sm:p-6">
      <div className="flex items-center gap-2">
        <History className="h-5 w-5 text-primary" />
        <h2 className="section-title">Recent import jobs</h2>
      </div>
      <div className="mt-4 grid gap-3">
        {jobs.length === 0 ? (
          <EmptyState title="No imports yet" description="Your recent bulk import jobs will appear here." />
        ) : jobs.map((job) => (
          <div key={job.id} className="rounded-2xl border border-border bg-surface-muted/20 p-4">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-sm font-semibold capitalize">{job.resource_type}</p>
                <p className="mt-1 text-xs text-text-muted">{formatDate(job.created_at)} · {job.original_filename}</p>
              </div>
              <div className="grid grid-cols-3 gap-2 text-center sm:min-w-[16rem]">
                <span className="rounded-xl bg-surface px-3 py-2 text-xs">Rows {job.total_rows}</span>
                <span className="rounded-xl bg-success-soft px-3 py-2 text-xs text-success">Ok {job.successful_rows}</span>
                <span className="rounded-xl bg-error-soft px-3 py-2 text-xs text-error">Bad {job.failed_rows}</span>
              </div>
              <Button variant="outline" size="sm" onClick={() => onSelectJob(job.id)}>
                View
              </Button>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}

function BulkImportPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [activeResource, setActiveResource] = useState("parents");
  const [file, setFile] = useState(null);
  const [currentJob, setCurrentJob] = useState(null);
  const [emailSummary, setEmailSummary] = useState(null);
  const [jobs, setJobs] = useState([]);
  const [loadingState, setLoadingState] = useState("idle");
  const [finishedToastJobId, setFinishedToastJobId] = useState(null);
  const { showSuccess, showError, showWarning, showInfo } = useToast();

  const selectedResource = useMemo(
    () => RESOURCE_OPTIONS.find((option) => option.key === activeResource) || RESOURCE_OPTIONS[0],
    [activeResource],
  );

  const persistActiveJob = useCallback((job) => {
    if (!job?.id) return;
    window.sessionStorage.setItem(ACTIVE_IMPORT_JOB_STORAGE_KEY, job.id);
    setSearchParams((current) => {
      const next = new URLSearchParams(current);
      next.set("job_id", job.id);
      return next;
    }, { replace: true });
  }, [setSearchParams]);

  const clearActiveJob = useCallback(() => {
    window.sessionStorage.removeItem(ACTIVE_IMPORT_JOB_STORAGE_KEY);
    setCurrentJob(null);
    setEmailSummary(null);
    setSearchParams((current) => {
      const next = new URLSearchParams(current);
      next.delete("job_id");
      return next;
    }, { replace: true });
  }, [setSearchParams]);

  const refreshEmailSummary = useCallback(async (job = currentJob) => {
    if (!job?.id || !["parents", "teachers"].includes(job.resource_type)) return;
    try {
      const summary = await bulkImportService.getEmailSummary({ source: "bulk_import" });
      setEmailSummary(summary);
    } catch (err) {
      showError(getErrorMessage(err, "Could not refresh email delivery status."));
    }
  }, [currentJob, showError]);

  const loadJobById = useCallback(async (jobId, { notify = false } = {}) => {
    if (!jobId) return null;
    try {
      const job = await bulkImportService.getJob(jobId);
      setCurrentJob(job);
      setActiveResource(job.resource_type || "parents");
      persistActiveJob(job);
      if (["parents", "teachers"].includes(job.resource_type)) {
        await refreshEmailSummary(job);
      }
      if (notify) showInfo("Import job restored.");
      return job;
    } catch (err) {
      showError(getErrorMessage(err, "Could not load import job."));
      return null;
    }
  }, [persistActiveJob, refreshEmailSummary, showError, showInfo]);

  const loadJobs = useCallback(async () => {
    try {
      const response = await bulkImportService.listJobs();
      setJobs(Array.isArray(response?.items) ? response.items : []);
    } catch {
      setJobs([]);
    }
  }, []);

  useEffect(() => {
    loadJobs();
    const jobId = searchParams.get("job_id") || window.sessionStorage.getItem(ACTIVE_IMPORT_JOB_STORAGE_KEY);
    if (jobId) loadJobById(jobId, { notify: false });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!isActiveJob(currentJob)) return undefined;

    const intervalId = window.setInterval(async () => {
      try {
        const freshJob = await bulkImportService.getJob(currentJob.id);
        setCurrentJob(freshJob);
        persistActiveJob(freshJob);

        if (isFinishedJob(freshJob)) {
          await loadJobs();
          await refreshEmailSummary(freshJob);
          if (finishedToastJobId !== freshJob.id) {
            setFinishedToastJobId(freshJob.id);
            if (freshJob.status === "failed") {
              showError("Import failed. Check the validation details for errors.", { duration: 5200 });
            } else {
              showSuccess("Import finished. Dashboard counts will refresh from the backend.", { duration: 5200 });
            }
          }
        }
      } catch (err) {
        showError(getErrorMessage(err, "Could not refresh import progress."));
      }
    }, 3000);

    return () => window.clearInterval(intervalId);
  }, [currentJob, finishedToastJobId, loadJobs, persistActiveJob, refreshEmailSummary, showError, showSuccess]);

  const handleDownloadTemplate = async (resourceType = activeResource) => {
    setLoadingState("template");
    try {
      await bulkImportService.downloadTemplate(resourceType);
      showSuccess("Template downloaded. Fill it without changing the headers.");
    } catch (err) {
      showError(getErrorMessage(err, "Template download failed."));
    } finally {
      setLoadingState("idle");
    }
  };

  const handleDryRun = async () => {
    if (!file) {
      showWarning("Choose the completed XLSX template before running dry-run.");
      return;
    }

    showInfo("Validating file...", { duration: 2200 });
    setLoadingState("dry-run");
    try {
      const job = await bulkImportService.dryRun(activeResource, file);
      setCurrentJob(job);
      setEmailSummary(null);
      persistActiveJob(job);
      showSuccess("Dry-run completed. Review the summary before confirming.");
      await loadJobs();
    } catch (err) {
      showError(getErrorMessage(err, "Dry-run failed."));
    } finally {
      setLoadingState("idle");
    }
  };

  const handleConfirm = async () => {
    if (!currentJob?.id || Number(currentJob.successful_rows || 0) <= 0) return;
    showInfo("Import queued. The progress bar will update automatically.", { duration: 4200 });
    setLoadingState("confirm");
    try {
      const job = await bulkImportService.confirm(currentJob.id);
      setCurrentJob(job);
      persistActiveJob(job);
      showSuccess("Import started in the background.", { duration: 4200 });
      await loadJobs();
    } catch (err) {
      showError(getErrorMessage(err, "Import confirmation failed."), { duration: 5200 });
    } finally {
      setLoadingState("idle");
    }
  };

  const handleDownloadResult = async () => {
    if (!currentJob?.id) return;
    try {
      await bulkImportService.downloadResult(currentJob.id);
      showSuccess("Result report downloaded.");
    } catch (err) {
      showError(getErrorMessage(err, "Result download failed."));
    }
  };

  const recoverStale = async () => {
    setLoadingState("email");
    try {
      await bulkImportService.recoverStaleEmails();
      await refreshEmailSummary();
      showSuccess("Stuck email jobs recovered where possible.");
    } catch (err) {
      showError(getErrorMessage(err, "Could not recover stale emails."));
    } finally {
      setLoadingState("idle");
    }
  };

  const retryFailed = async () => {
    setLoadingState("email");
    try {
      await bulkImportService.retryFailedEmails();
      await refreshEmailSummary();
      showSuccess("Failed emails were queued for retry where possible.");
    } catch (err) {
      showError(getErrorMessage(err, "Could not retry failed emails."));
    } finally {
      setLoadingState("idle");
    }
  };

  const busy = loadingState !== "idle";
  const confirmable = currentJob?.id && Number(currentJob.successful_rows || 0) > 0 && currentJob.metadata_json?.dry_run !== false;

  return (
    <DashboardLayout
      role="admin"
      title="Bulk Imports"
      description="Create students, teachers, and parents from backend-generated XLSX templates with dry-run validation first."
      actions={<Button variant="outline" onClick={() => handleDownloadTemplate(activeResource)} disabled={busy}><Download className="h-4 w-4" />Download template</Button>}
    >
      {isActiveJob(currentJob) ? <LoadingState label="Import is running in the background. Progress refreshes every few seconds..." /> : null}

      <JobSummary job={currentJob} onClear={clearActiveJob} />

      <section className="grid gap-4 lg:grid-cols-3">
        {RESOURCE_OPTIONS.map((option) => (
          <ResourceCard
            key={option.key}
            option={option}
            active={option.key === activeResource}
            onSelect={(key) => { setActiveResource(key); setFile(null); setCurrentJob(null); setEmailSummary(null); }}
            onDownload={handleDownloadTemplate}
            isDownloading={loadingState === "template"}
          />
        ))}
      </section>

      <section className="dashboard-grid lg:grid-cols-[minmax(0,1.05fr)_minmax(300px,0.95fr)]">
        <Card className="p-5 sm:p-6">
          <div className="flex flex-col gap-4">
            <div>
              <h2 className="section-title">Upload completed template</h2>
              <p className="mt-1 text-sm text-text-muted">Selected import: <span className="font-semibold text-text">{selectedResource.label}</span></p>
            </div>
            <label className="flex cursor-pointer flex-col items-center justify-center rounded-[1.75rem] border border-dashed border-border bg-surface-muted/20 px-4 py-8 text-center transition hover:border-primary/50 hover:bg-primary-soft/20">
              <UploadCloud className="h-10 w-10 text-primary" />
              <span className="mt-3 text-sm font-semibold text-text">{file ? file.name : "Choose XLSX file"}</span>
              <span className="mt-1 text-xs text-text-muted">Only backend-generated .xlsx templates are accepted.</span>
              <input type="file" accept=".xlsx" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] || null)} />
            </label>
            <div className="grid gap-3 sm:grid-cols-2">
              <Button variant="outline" onClick={() => handleDownloadTemplate(activeResource)} disabled={busy}><Download className="h-4 w-4" />Download fresh template</Button>
              <Button onClick={handleDryRun} disabled={busy || !file}>{loadingState === "dry-run" ? <RefreshCw className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Run dry-run</Button>
            </div>
          </div>
        </Card>

        <Card className="p-5 sm:p-6">
          <h2 className="section-title">How this works</h2>
          <div className="mt-4 grid gap-3">
            {["Download the signed XLSX template.", "Fill rows without changing headers.", "Run dry-run to catch row errors.", "Confirm only valid staged rows.", "Watch live import progress after confirmation."].map((item, index) => (
              <div key={item} className="flex gap-3 rounded-2xl border border-border bg-surface-muted/20 px-4 py-3">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">{index + 1}</span>
                <p className="text-sm leading-6 text-text-soft">{item}</p>
              </div>
            ))}
          </div>
        </Card>
      </section>

      <ErrorPreview job={currentJob} onDownloadResult={handleDownloadResult} />

      {confirmable ? (
        <Card className="p-5 sm:p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="section-title">Ready to confirm</h2>
              <p className="mt-1 text-sm text-text-muted">This will create {currentJob.successful_rows} {currentJob.resource_type} records. After confirmation, this page will poll the backend for live progress.</p>
            </div>
            <Button className="w-full sm:w-auto" onClick={handleConfirm} disabled={busy}>{loadingState === "confirm" ? <RefreshCw className="h-4 w-4 animate-spin" /> : null}Confirm import</Button>
          </div>
        </Card>
      ) : null}

      <EmailStatusPanel
        summary={emailSummary}
        onRefresh={() => refreshEmailSummary()}
        onRecover={recoverStale}
        onRetry={retryFailed}
        loading={loadingState === "email"}
      />

      <JobHistory jobs={jobs} onSelectJob={(jobId) => loadJobById(jobId, { notify: true })} />
    </DashboardLayout>
  );
}

export default BulkImportPage;
